name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t app .

      - name: Run tests inside Docker
        run: docker run --rm -v ${{ github.workspace }}:/app app

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest.xml
